### ISSUE TITLE
Reviews image

### ISSUE THREAD

**Issue by othmane-ba** [sonsalem/Template-Cycle#1]
It's a beautiful and creative design. Just one small thing,the reviews picture is a bit stretched

**Comment by AbdelrahmanJu** [comment]
Agree with the previous comment
And also you're missing a "Submit" button for the newsletter subscription
Excellent work 
Keep it up

**Comment by sonsalem** [comment]
I add submit button but I don't get it how picture is a bit stretched i'm still a junior can you explain more clear

**Comment by othmane-ba** [comment]
all you have to do is to add  object-fit: cover; tou your image class

this was your old code:
.say .container .content .image img {
    height: 100%;
    max-width: 100%;
}

and this is how it should look like
.say .container .content .image img {
    object-fit: cover;
    height: 100%;
    max-width: 100%;
}

**Comment by sonsalem** [comment]
Thanks I get it

**Comment by othmane-ba** [comment]
You're welcome
